//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRHH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidatos
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Cedula { get; set; }
        public int IdPuestos { get; set; }
        public int IdDeparamento { get; set; }
        public decimal SalarioDeseado { get; set; }
        public string Competencias { get; set; }
        public string Capacitaciones { get; set; }
        public string Experiencia { get; set; }
        public string Recomendacion { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        public virtual ExperienciaLaboral ExperienciaLaboral { get; set; }
        public virtual Puestos Puestos { get; set; }
    }
}
