//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRHH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Cedula { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public int IdDepartamento { get; set; }
        public int IdPuesto { get; set; }
        public decimal Salario { get; set; }
        public bool Estado { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        public virtual Puestos Puestos { get; set; }
    }
}
