//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRHH
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExperienciaLaboral
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExperienciaLaboral()
        {
            this.Candidatos = new HashSet<Candidatos>();
        }
    
        public int IdCandidato { get; set; }
        public string Empresa { get; set; }
        public string Puesto { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFinalizacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Candidatos> Candidatos { get; set; }
    }
}
